### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Eug325** [SegiH/Emby-and-Jellyfin-Playlist-Exporter#4]
Hi , i try this but is not working , input the server ip /host and api is asking to chose a user 
And a destination all set byt when i press on playlist button , no playlist is showing  up .

**Comment by SegiH** [comment]
Hi are you getting an error ?

Did you select a user from the user drop down?

Can you send me a screenshot of the app with the sensitive info like url and api keys

**Comment by Eug325** [comment]
There is no error showing up .Yes no problem https://emby.seresme.com/
API: 636799b69446425c89372b6dd368495d

The api will be deleted after you replay Thanks

    On Friday, February 28, 2025 at 01:05:08 AM GMT, Segi ***@***.***> wrote:  
 
  
Hi are you getting an error ?

Did you select a user from the user drop down?

Can you send me a screenshot of the app with the sensitive info like url and api keys

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>
SegiH left a comment (SegiH/Emby-and-Jellyfin-Playlist-Exporter#4)
Hi are you getting an error ?

Did you select a user from the user drop down?

Can you send me a screenshot of the app with the sensitive info like url and api keys

**Comment by SegiH** [comment]
Ok let me look into this further

**Comment by SegiH** [comment]
I just did a test. When I wrote this app, I was still using Emby but wrote it to support both Emby and Jellyfin but I have since moved on to Jellyfin.

I tested my app using Jellyfin and it works. 

When I test it with Emby it returns no results.

I think that there was a change on the Emby side and I think I know how to fix it.

Please confirm that these are the names of your playlists: 

Live TV
4K
EN 1
EN 2
1Ro
1En
2En
3En
Movies pc

**Comment by Eug325** [comment]
Hi , Greate  good news,  Thank you very much  , yes that are my folders on my pc what is linked to Emby 

Actually playlist in Emby are 
Live tv
Filme
Filme 4K
Filme p
Seriale EN
I am using version 4.9.0.40 Beta in Emby

Yahoo Mail – Email Simplified 
 
  On Fri, 28 Feb 2025 at 2:29, ***@***.***> wrote:    
I just did a test. When I wrote this app, I was still using Emby but wrote it to support both Emby and Jellyfin but I have since moved on to Jellyfin.

I tested my app using Jellyfin and it works.

When I test it with Emby it returns no results.

I think that there was a change on the Emby side and I think I know how to fix it.

Please confirm that these are the names of your playlists:

Live TV
4K
EN 1
EN 2
1Ro
1En
2En
3En
Movies pc

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>
SegiH left a comment (SegiH/Emby-and-Jellyfin-Playlist-Exporter#4)
I just did a test. When I wrote this app, I was still using Emby but wrote it to support both Emby and Jellyfin but I have since moved on to Jellyfin.

I tested my app using Jellyfin and it works.

When I test it with Emby it returns no results.

I think that there was a change on the Emby side and I think I know how to fix it.

Please confirm that these are the names of your playlists:

Live TV
4K
EN 1
EN 2
1Ro
1En
2En
3En
Movies pc

**Comment by SegiH** [comment]
Ok I am working on a fix for this

**Comment by SegiH** [comment]
Hi

I just published a new release that works with the latest version of Emby and Jellyfin. Please try it out

**Comment by Eug325** [comment]
Hi , i try out the script and is not working :-(
When I select Emby 
I insert url and api and it just show folder to download i select folder and that is it noting more no user to selec
When i select Jellyfin insert url and api for Emby hit connect and is showing to select user name , select user name and select folder and that is it 
Can we speak somewhere more private? Thanks 

Yahoo Mail – Email Simplified 
 
  On Mon, 3 Mar 2025 at 9:46, jeno ***@***.***> wrote:   
Hi , I will try it out later and give you a feedback,  Thank you 

Yahoo Mail – Email Simplified 
 
  On Mon, 3 Mar 2025 at 6:34, ***@***.***> wrote:    
Hi

I just published a new release that works with the latest version of Emby and Jellyfin. Please try it out

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>
SegiH left a comment (SegiH/Emby-and-Jellyfin-Playlist-Exporter#4)
Hi

I just published a new release that works with the latest version of Emby and Jellyfin. Please try it out

**Comment by SegiH** [comment]
When you are using emby you don't select a user. That's specific to jellyfin.

Can you send me a screenshot. I tested this with Emby and Jellyfin yesterday and it worked fine for both

**Comment by SegiH** [comment]
If you would like to talk further outside of Github, we can chat on IRC or Matrix

**Comment by SegiH** [comment]
Hi

I see you closed this issue. Just wanted to let you know that I published a new update that has many fixes and I would strongly suggest running the latest build

**Comment by Eug325** [comment]
Hi, I just check the new release but is still not working , maybe is something with my pc .I attached a photo Thanks
    On Monday, March 10, 2025 at 09:29:24 PM GMT, Segi ***@***.***> wrote:  
 
  
Hi

I see you closed this issue. Just wanted to let you know that I published a new update that has many fixes and I would strongly suggest running the latest build

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you modified the open/close state.Message ID: ***@***.***>
SegiH left a comment (SegiH/Emby-and-Jellyfin-Playlist-Exporter#4)
Hi

I see you closed this issue. Just wanted to let you know that I published a new update that has many fixes and I would strongly suggest running the latest build

**Comment by SegiH** [comment]
I'm sorry but I dont see an attached image.

What's the error message ?

I tested my app extensively with both Jellyfin and Emby before publishing this release. Make sure you enter the emby url as http://localhost:8096 with nothing after that and also make sure that the API key is valid

**Comment by Eug325** [comment]
There is no error message it connects  but is not showing any playlist is the same like previous versions,  I'm not sure what is going on .
If i take url out is giving me a error message saying is not the right url or api
I tried with http local and https domain 


Yahoo Mail – Email Simplified 
 
  On Tue, 11 Mar 2025 at 20:17, ***@***.***> wrote:    
I'm sorry but I dont see an attached image.

What's the error message ?

I tested my app extensively with both Jellyfin and Emby before publishing this release. Make sure you enter the emby url as http://localhost:8096 with nothing after that

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you modified the open/close state.Message ID: ***@***.***>
SegiH left a comment (SegiH/Emby-and-Jellyfin-Playlist-Exporter#4)
I'm sorry but I dont see an attached image.

What's the error message ?

I tested my app extensively with both Jellyfin and Emby before publishing this release. Make sure you enter the emby url as http://localhost:8096 with nothing after that

**Comment by SegiH** [comment]
Do you use IRC or discord? We should probably discuss this somewhere in private so you can give me the url to your media server and api key so I can test this out.

**Comment by SegiH** [comment]
I also thought of something else. Make sure that you do not have any firewalls blocking the apps connection to your media server.

**Comment by Eug325** [comment]
I use discord

Yahoo Mail – Email Simplified 
 
  On Tue, 11 Mar 2025 at 20:31, ***@***.***> wrote:    
I also thought of something else. Make sure that you do not have any firewalls blocking the apps connection to your media server.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you modified the open/close state.Message ID: ***@***.***>
SegiH left a comment (SegiH/Emby-and-Jellyfin-Playlist-Exporter#4)
I also thought of something else. Make sure that you do not have any firewalls blocking the apps connection to your media server.

**Comment by SegiH** [comment]
Can you please send me your discord username

**Comment by Eug325** [comment]
Yes is eug3n9

Yahoo Mail – Email Simplified 
 
  On Tue, 11 Mar 2025 at 21:22, ***@***.***> wrote:    
Can you please send me your discord username

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you modified the open/close state.Message ID: ***@***.***>
SegiH left a comment (SegiH/Emby-and-Jellyfin-Playlist-Exporter#4)
Can you please send me your discord username

**Comment by SegiH** [comment]
I sent you a friend request there

**Comment by SegiH** [comment]
Im closing this because of a lack of response
